### PR TITLE
Changes for Python 3 compatibility

### PR DESCRIPTION
**Pull request by rgerkin**
Required for the README instructions at https://github.com/openworm/muscle_model to work in Python 3.

### CODE REVIEW

**Comment by adrianq** [comment]
@rgerkin @pgleeson Sorry, don't realise about this PR. Is this sth we still want to merge into the master branch?

**Comment by rgerkin** [comment]
Sorry, I didn't notice the travis build failed.  I think it was due to something I did locally to get Python 3's annoying import rules to work.  I'll fix that and repush.

**Comment by pgleeson** [comment]
This doesn't seem to be working in Python 2 @rgerkin... Test fails...

**Comment by rgerkin** [comment]
I'll deal with this in a few days.

**Comment by rgerkin** [comment]
@pgleeson Fixed.

**Comment by adrianq** [comment]
@pgleeson are you merging this finally? Do you want me to do it?

**Comment by pgleeson** [comment]
Want to test this with some other scripts using the OSB API, so it will have to wait until after OSB workshop I'm afraid...

**Comment by pgleeson** [comment]
@rgerkin Sorry it's taken so long to get this merged... Have tidied it up a bit & updated it with better P3 support.

**Pull request merged**
